### PR TITLE
Adds TransformEditor

### PR DESCRIPTION
**Pull request by petereichinger**
Improved editor for transform component with reset buttons

### CODE REVIEW

**Comment by nickgravelyn** [comment]
Thanks for contributing to the library!

However I'm not going to merge in this editor because I'm not a fan of extensions that modify the default editors of built-in components. Given that a number of users bring in UnityToolbag as a submodule (which includes all code), there would be no way for those users to easily disable this without deleting or modifying the code which is less than ideal.

**Comment by petereichinger** [comment]
Ok, no worries.

Totally understand why you don't want it.
Just felt like sharing :smile:.

Are there any things you'd like to see added?

**Comment by nickgravelyn** [comment]
Nothing specifically that I can think of. Nobody's asked me for anything at this point either.

**Comment by petereichinger** [comment]
If I write anything again that looks useful to others I'll make another
pull request.

I really appreciate this repo and the work you put in.

**Pull request closed without merging**
