### PR TITLE
Quick Toggle Updates

### PR DESCRIPTION
**Pull request by ChemiKhazi**
Enhancements to quick toggle that make it act more like Photoshop, allowing for quicker mass object toggling.

### CODE REVIEW

**Comment by nickgravelyn** [comment]
Would you be willing to make a repo for your Quick Toggle? Especially for things like these editor integrations, I'd like to avoid having them all hosted in my repo, mainly because I become a bottleneck. I'd be happy to replace the code in my repo with a note and a link to your repo in that case.

**Comment by ChemiKhazi** [comment]
I could change the main README of my fork of your repo to have an additional section highlighting the editor extensions I maintain.

**Comment by nickgravelyn** [comment]
Thanks but I'd rather the tools not be maintained in my repo anymore. Nothing personal, but I just want to avoid bloating this repo too much and want to make sure I don't have to accept PRs for you to update your tools.

**Comment by ChemiKhazi** [comment]
I'm thinking the strategy would be that I don't make PRs to your repo, I'd just continue development on my fork and pulling your updates into my repo but not the other way around. That way I get to keep my repo up to date with your tools while I keep development of my tools.

**Comment by nickgravelyn** [comment]
I think in that case it'd be best for you to instead use a Git submodule or just write your repo assuming mine is already cloned, then I'd be fine pointing folks to your repo via my readme.

Or you're always welcome to maintain your own fork as you want, but in that case I wouldn't put a link in my readme since your fork would just be a separate fork of the repo and I don't want to get in the habit of linking to forks given this repo has 134 of them already.

**Pull request closed without merging**
