### PR TITLE
Added Events system

### PR DESCRIPTION
**Pull request by Cotoff**
I've added a system for fast, type-safe SendMessage replacement.

### CODE REVIEW

**Comment by vicenterusso** [comment]
Is it technically different from [Advanced CSharp Messenger](http://wiki.unity3d.com/index.php?title=Advanced_CSharp_Messenger)? I have used this one and I had some problems with [ExecuteInEditMode] and removing listeners and stuff. Do you have it covered in your SendMessage replacement?

**Comment by Cotoff** [comment]
It's WAY simpler than that. There are no listeners and subscriptions and nothing remove - just a way to enumerate all components and call a method without memory allocation.

**Comment by nickgravelyn** [comment]
Sorry for the late review. I rather like the enumeration parts of this, but I'm not as big of a fan of the "event" part for a few reasons:

- The Send methods are trivial wrappers around the nice enumeration so IMO don't provide a ton of value.
- Passing in a lambda to the methods will (in most cases, IIRC) allocate due to captures and whatnot, so the Send methods aren't quite as garbage free as advertised.

I'd be interested in taking in a PR that was just the helpers around enumerating components with the cached lists, but I think the events bit is trying to be more clever than needs be, given how nice the enumeration makes simple foreach loops.

**Comment by Cotoff** [comment]
That makes sense. I've originally intended to replace SendMessage functionality, so the Send(Action) interface seemed logical; and I made the enumeration method as one step on the way. But maybe simply using foreach would be better.. I'll make the enumerating-only PR sometime soon.

**Comment by nickgravelyn** [comment]
If you'd like, I'm starting a new group on Github (https://github.com/UnityCommunity) to try and break UnityToolbag into separate projects so it's easier to maintain and easier to have multiple contributors. If you wanted, I can invite you to that group so you can make a new repo there. I plan to do less curation there than in UnityToolbag (which likely will become less and less updated), so you could have a repo in the community for your enumeration and actions if you'd like to continue supporting them.

**Comment by Cotoff** [comment]
That's a nice idea, a group of projects instead of one catch-all. Yeah, I'd like an invite.

**Pull request closed without merging**
